<a href="https://colab.research.google.com/github/jericgiron/Numerical-Method/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Matrix And Its Operations

In [1]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
import numpy as np
b = np.array([[1,2,3],
              [4,5,6]])
b[0,0] = 7
print(b)
print(b.size)
print(b.shape)

[[7 2 3]
 [4 5 6]]
6
(2, 3)


In [25]:
import numpy as np
c = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(c)
print(c.size)
print(c.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9
(3, 3)


In [23]:
import numpy as np
d = np.full((2,2),4)
d

array([[4, 4],
       [4, 4]])

In [22]:
import numpy as np
e = np.eye(5)
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
diagonal = np.array([[9,0,0],
                     [0,6,0],
                     [0,0,3],
                     ])
diagonal

array([[9, 0, 0],
       [0, 6, 0],
       [0, 0, 3]])

In [31]:
Diagonal = np.diag([9,6,3])
Diagonal

array([[9, 0, 0],
       [0, 6, 0],
       [0, 0, 3]])

In [32]:
Zero = np.zeros((5,5))
Zero


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])