<a href="https://colab.research.google.com/github/jericgiron/Numerical-Method/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix and Its Operations

## 1. sum = A +B


In [2]:
import numpy as np

A = np.array([
    [-5,0],
    [4,1]
])
B = np.array([
    [6,-3],
    [2,3]
])

A + B

array([[ 1, -3],
       [ 6,  4]])

## 2. Difference1 = B - A

In [3]:
B-A

array([[11, -3],
       [-2,  2]])

## 3. Difference2 = A - B

In [4]:
A - B

array([[-11,   3],
       [  2,  -2]])